### ISSUE TITLE
No script for downloading qsattn dataset.

### ISSUE THREAD

**Issue by Kravrolens** [sapphire497/query-selected-attention#5]
Hi, Thank you for the awesome work.

It seems that `/download_qsattn_dataset.sh`  does not exists, could you please share the code? Thanks.

**Comment by Kravrolens** [comment]
OK, I've got it.

**Comment by PinPointPing** [comment]
Where is it?

**Comment by PinPointPing** [comment]
I guess you can get it from [Kaggle](https://www.kaggle.com/datasets/balraj98/horse2zebra-dataset).
