### ISSUE TITLE
关于评价指标计算

### ISSUE THREAD

**Issue by KevinMarkVine** [sapphire497/query-selected-attention#7]
您好，关于您工作，我有两个问题想请问一下：
1. 您论文中的FID和SWD得分结果是按照CUT和F-LSeSim的方式来计算的吗，即，计算每个epoch的FID结果，取最优值
2. SWD得分的计算方式和上述一样吗，SWD的得分与FID是否是同一个epoch的模型的结果呢，还是各自取最优

**Comment by sapphire497** [comment]
1. 是的。
2. FID和SWD是同一个模型的结果。
