### ISSUE TITLE
When does netF send loss backward to calculate the gradients?

### ISSUE THREAD

**Issue by Mahmood-Hussain** [sapphire497/query-selected-attention#8]
Hello,

The method that you use as your inspiration F-LSeSim has a function to send gradients of netF backward but I can not see it in your code how does it gets trained? am I missing something?
![image](https://user-images.githubusercontent.com/31275645/184612615-71410831-1b8d-4d41-81fc-5ecd1def6a04.png)

But there is no backward function for your code I am not sure if there is something wrong or if I don't have enough knowledge.

**Comment by sapphire497** [comment]
We optimize net_F by the loss_NCE in the function backward_G.
