### ISSUE TITLE
Pared I2I

### ISSUE THREAD

**Issue by PinPointPing** [sapphire497/query-selected-attention#9]
Can this repo be used for paired I2I like pix2pix? I would like to use if for that purpose but I can't seem to find how exactly. I see some cityscapes in the teaser image so I would assume it's possible.

**Comment by sapphire497** [comment]
Yes, the model can be used for paired datasets, but we don't use the paired image to be ground truth, i.e., we consider the paired dataset as unpaired dataset during the training.

**Comment by Mahmood-Hussain** [comment]
I that case do you expect training samples to be paired during training? 
I have a paired mask to rgb image dataset but when I see visuals produced during training epochxxx_real_A.png, epochxxx_real_B.png, epochxxx_fake_B.png seem all to be different. Is this okay if we want to train a mask to rgb image?

should we expect correct rgb output at the time of inference?
